application: observe-or-guess
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /html
  static_dir: html

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /.*
  script: backend.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
builtins:
  - remote_api: on
